name: Update the legacy-v1 branch when a release is published
on:
  release:
    types: [published]
jobs:
  release:
    if: startsWith(env.GITHUB_REF, 'legacy-v1.')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: git push origin HEAD:legacy-v1
